
name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create the network
        run: docker network create machinerie-network
      - name: Build the stack
        run: docker-compose up -d
        env:
          ENTRYPOINT: http
          NETWORK: machinerie-network
      - name: HTTP test
        run: docker run --network container:botly-studio appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/
